In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [2]:
from src.data.load_data import load_data

In [3]:
df = load_data()

DEBUG PATH: d:\student-depression-dl\data\raw\Student-Depression-Dataset.csv

In [4]:
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33,Visakhapatnam,Student,5,0,8.97,2,0,5-6 hours,Healthy,B.Pharm,Yes,3,1.0,No,1
1,8,Female,24,Bangalore,Student,2,0,5.90,5,0,5-6 hours,Moderate,BSc,No,3,2.0,Yes,0
2,26,Male,31,Srinagar,Student,3,0,7.03,5,0,Less than 5 hours,Healthy,BA,No,9,1.0,Yes,0
3,30,Female,28,Varanasi,Student,3,0,5.59,2,0,7-8 hours,Moderate,BCA,Yes,4,5.0,Yes,1
4,32,Female,25,Jaipur,Student,4,0,8.13,3,0,5-6 hours,Moderate,M.Tech,Yes,1,1.0,No,0

In [5]:
from src.data.preprocess import preprocess_data

df_clean = preprocess_data(df)
df_clean.head()

,Gender,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,Dietary Habits_Moderate,Dietary Habits_Others,Dietary Habits_Unhealthy
0,0,1.463165,5,0,0.893393,2,0,1.0,1,-1.121213,1.0,0,1,0,0,0
1,1,-0.371474,2,0,-1.194076,5,0,1.0,0,-1.121213,2.0,1,0,1,0,0
2,0,1.055467,3,0,-0.425724,5,0,0.0,0,0.497095,1.0,1,0,0,0,0
3,1,0.443921,3,0,-1.404862,2,0,2.0,1,-0.851495,5.0,1,1,1,0,0
4,1,-0.167625,4,0,0.322229,3,0,1.0,1,-1.660650,1.0,0,0,1,0,0

In [7]:
df_clean.isnull().sum()
df_clean.dtypes

Gender                                     int64
Age                                      float64
Academic Pressure                          int64
Work Pressure                              int64
CGPA                                     float64
Study Satisfaction                         int64
Job Satisfaction                           int64
Sleep Duration                           float64
Have you ever had suicidal thoughts ?      int64
Work/Study Hours                         float64
Financial Stress                         float64
Family History of Mental Illness           int64
Depression                                 int64
Dietary Habits_Moderate                    int32
Dietary Habits_Others                      int32
Dietary Habits_Unhealthy                   int32
dtype: object